### ISSUE TITLE
有时开启应用等情况下会报fab的空指针

### ISSUE THREAD

**Issue by AltairT** [DanteAndroid/Beauty#2]
# 系统版本
GenyMotion 版本 5.0  API21
# 发生条件
- 打开应用时几率发生
- 在`应用信息`页面返回时几率发生 

# LOGCAT
```javascript
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBarDrawerToggle.setToolbarNavigationClickListener(android.view.View$OnClickListener)' on a null object reference
                                                                     at com.dante.girls.MainActivity.initFab(MainActivity.java:203)
                                                                     at com.dante.girls.MainActivity.initToolbar(MainActivity.java:115)
                                                                     at com.dante.girls.MainActivity.initViews(MainActivity.java:100)
                                                                     at com.dante.girls.base.BaseActivity.onCreate(BaseActivity.java:35)
```
# 我还是个**菜鸡**，`大佬`自己修吧

**Comment by DanteAndroid** [comment]
已經更新apk
